### ISSUE TITLE
在修改配置文件后在页面上没有生效！

### ISSUE THREAD

**Issue by lovehuiyuanai** [can-dy-jack/hexo-theme-delicate#16]
在修改配置文件后在页面上没有生效！

**Comment by can-dy-jack** [comment]
请按照说明文件进行尝试：
![image](https://github.com/can-dy-jack/hexo-theme-delicate/assets/62332701/e72be607-59d5-45c1-9379-08a0b3543ae2)

请确认：
1. 正确安装主题插件
2. 在根目录下的配置文件正确配置为本主题
3. 根配置文件修改后，需要重启项目才能生效，请确认已重启也不行
